-- 코드를 입력하세요
SELECT SUBSTR(SALES_DATE, 1, 10) as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE
where SUBSTR(SALES_DATE, 1, 7) = '2022-03'
union
SELECT SUBSTR(SALES_DATE, 1, 10) as SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
from OFFLINE_SALE
where SUBSTR(SALES_DATE, 1, 7) = '2022-03'
order by SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC