-- 코드를 작성해주세요
SELECT CASE
WHEN SKILL_CODE & (SELECT CODE from SKILLCODES where NAME = 'Python') and
SKILL_CODE & (SELECT sum(CODE) from SKILLCODES where CATEGORY = 'Front End')
THEN 'A'
WHEN SKILL_CODE & (SELECT CODE from SKILLCODES where NAME = 'C#')
THEN 'B'
WHEN SKILL_CODE & (SELECT sum(CODE) FROM SKILLCODES where CATEGORY = 'Front End')
THEN 'C' 
ELSE NULL END GRADE,
ID, EMAIL
FROM DEVELOPERS
HAVING GRADE is not null
order by GRADE asc, ID ASC